INSERT INTO public.logistica (nombre_manual, voter_id, categoria) VALUES
('NURY MILENA RIAÑO', NULL, 'JURADOS REMANENTES'),
('DONY ALEXANDER ÁVILA LOPEZ', NULL, 'JURADOS REMANENTES'),
('ZULAY ALEXANDRA ALVARADO NAVARRO', NULL, 'JURADOS REMANENTES'),
('SHAILY STEFANNY MARROQUIN GARCÍA', NULL, 'JURADOS REMANENTES'),
('MARCELA MILENA LINARES SOSSA', NULL, 'JURADOS REMANENTES'),
('ANDRES HERNANDEZ LONDOÑO', NULL, 'JURADOS REMANENTES'),
('DIEGO CASTAÑO FRANCO', NULL, 'JURADOS REMANENTES'),
('JAIRO HUMBERTO PINILLA AFANADOR', NULL, 'JURADOS REMANENTES'),
('HECTOR IVAN MENA ARANGO', NULL, 'JURADOS REMANENTES'),
('JUAN DIEGO ACELAS VARGAS', NULL, 'JURADOS REMANENTES'),
('LUIS ARROYAVE', NULL, 'APOYO ELECTORAL'),
('SUGGEIN', NULL, 'APOYO ELECTORAL'),
('CARLOS RIVERA', NULL, 'COORDINADOR'),
('JULIANA ARIAS', NULL, 'REMANENTE'),
('Isabel Ardila', NULL, 'REMANENTE'),
('Maria Eugenia Gonzalez', NULL, 'REMANENTE'),
('Edison Estrada', NULL, 'REMANENTE'),
('Oscar Iván Calle', NULL, 'REMANENTE'),
('Michelle Moreno', NULL, 'REMANENTE'),
('Nazly Martinez', NULL, 'REMANENTE'),
('Nila Estupiñan', NULL, 'JURADOS'),
('Gustavo Restrepo', NULL, 'JURADOS'),
('Nélson Galan', NULL, 'JURADOS'),
('NéstorAcevedo', NULL, 'JURADOS'),
('Rodolfo Martínez', NULL, 'JURADOS'),
('Andrés Canal', NULL, 'JURADOS'),
('Alexander Aguirre', NULL, 'JURADOS'),
('PATRICIA LONDOÑO', NULL, 'PATRICIA LONDOÑO / JOSE'),
('JOSE', NULL, 'PATRICIA LONDOÑO / JOSE'),
('CRISTIAN ARROYAVE', NULL, 'CONSOLIDACIÓN ESCRUTINIOS'),
('LILY ROJAS', NULL, 'TRANSPORTE - APOYO'),
('Patricia Londoño', NULL, 'TRANSPORTE - Valencia (Viernes)'),
('Jairo Ramírez', NULL, 'TRANSPORTE - ALICANTE'),
('Jhon Tello', NULL, 'TRANSPORTE - ALICANTE'),
('Alex Trujillo', NULL, 'TRANSPORTE - ALICANTE'),
('Geovanny Posada', NULL, 'TRANSPORTE - PETRER'),
('Wilmar Salazar', NULL, 'TRANSPORTE - PETRER'),
('Yorjan Muñoz', NULL, 'TRANSPORTE - PETRER'),
('Roberto Romero', NULL, 'TRANSPORTE - VALENCIA'),
('Piedad Perez', NULL, 'TRANSPORTE - BENIDORM'),
('Antonio Diaz', NULL, 'TRANSPORTE - BENIDORM'),
('JOSE', NULL, 'ALIMENTACIÓN'),
('Nelcy Uribe', NULL, 'ALIMENTACIÓN'),
('Juan Mañas', NULL, 'ALIMENTACIÓN'),
('Andrés Bermudez', NULL, 'ALIMENTACIÓN'),
('Matilde Isignares', NULL, 'ALIMENTACIÓN'),
('LUIS ARROYAVE', NULL, 'LOGÍSTICA'),
('DIANA Amirtidad', NULL, 'ENTREGA DE ALIMENTOS E IMPREVISTOS'),
('MARIA ENITH', NULL, 'PEDAGOGÍA IGLESIA'),
('MARIA ALEJANDRA', NULL, 'PEDAGOGÍA APOYO'),
('Cecilia', NULL, 'PEDAGOGÍA - Alicante'),
('esposo de Cecilia', NULL, 'PEDAGOGÍA - Alicante'),
('Elina Figueroa', NULL, 'PEDAGOGÍA - Alicante'),
('Consuelo Villegas', NULL, 'PEDAGOGÍA - Alicante'),
('Esperanza Rojas', NULL, 'PEDAGOGÍA - Alicante'),
('Yudy Homez', NULL, 'PEDAGOGÍA - Alicante'),
('Alba Marroquin', NULL, 'PEDAGOGÍA - Alicante'),
('Monica Espinal', NULL, 'PEDAGOGÍA - Alicante'),
('Yenevye Mayorga', NULL, 'PEDAGOGÍA - Benidorm'),
('Karen Mayorga', NULL, 'PEDAGOGÍA - Benidorm'),
('Estefania Salazar', NULL, 'PEDAGOGÍA - Petrer'),
('Nohara Saavedra', NULL, 'PEDAGOGÍA - Petrer'),
('CRISTIAN', NULL, 'LLEVAR A PUNTO DE VOTACIÓN'),
('Elvira', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Alicante'),
('Piero Solari', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Alicante'),
('Lorena', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Alicante'),
('Ivette', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Alicante'),
('Milton Valencia', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Alicante'),
('Luz Marina Mayorga', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Benidorm'),
('Yamilet Mayorga', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Benidorm'),
('Ma. Eugenia Polentino', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Benidorm'),
('Juan Carlos', NULL, 'LLEVAR A PUNTO DE VOTACIÓN - Benidorm'),
('PATRICIA AGUIRRE', NULL, 'CALL CENTER'),
('Delban', NULL, 'CALL CENTER - Iglesia'),
('Jacobo Arroyave', NULL, 'CALL CENTER - Iglesia'),
('Angela Forero', NULL, 'CALL CENTER - Iglesia'),
('Daniela Lamus', NULL, 'CALL CENTER - Hotel'),
('Jenifer López', NULL, 'CALL CENTER - Hotel');